### ISSUE TITLE
Give random file names to trace file

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/2048#13]
Here is a neat trick you can use to get random names.

'''
import uudi
id = uuid.uuid4()
print (id4.node)
195991482805691
'''

Have a naming convention and add this string at the end. E.g.
2048trace_195991482805691.csv

**Comment by ajkim0630** [comment]
Traceback (most recent call last):
  File "C:/Users/Lexi/Documents/Git/2048/2048.py", line 3, in <module>
    import uudi
ModuleNotFoundError: No module named 'uudi'

**Comment by jybluekim** [comment]
Sorry I meant uuid and not uudi. 

Should have been obvious from the 2nd line!!

**Comment by ajkim0630** [comment]
File "C:/Users/Lexi/Documents/Git/2048/2048.py", line 161, in main
    filename = '2048trace_' + str(id4.node)
NameError: name 'id4' is not defined

**Comment by ajkim0630** [comment]
done
