### ISSUE TITLE
Figure out the effectiveness of different algorithm

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/2048#15]
Hi,

Once you modularize the algorithm part, I want you to be able to run different algorithms n times (usually n=30 would be good) and compare how these algorithms fare. This what I wanted initially but I think you prematurely closed it. 

https://github.com/ajkim0630/2048/issues/11

So say you have 5 different algorithms. Write a "wrapper" function that runs each algo 30 times and compare the following numbers.

* Max number achieves (over 30 tries)
* Average max number (averaged over 30 runs)
* Average # of moves (over 30 runs)

This will give you decent ideas about how good each algo is.

**Comment by ajkim0630** [comment]
done also i got 512 once according to this function
