### ISSUE TITLE
Use raw_input() instead of input()

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/2048#22]
Somehow in Mac, input() is not working.

Use raw_input() instead and see if it works on Windows.

**Comment by ajkim0630** [comment]
raw_input doesn't work for me

**Comment by ajkim0630** [comment]
raw input doesn't work for me so i'll just close this

**Comment by jybluekim** [comment]
At minimum do this

https://stackoverflow.com/questions/8220108/how-do-i-check-the-operating-system-in-python

Look at the first answer there. If platform is darwin then do raw_input(), else, input().

**Comment by ajkim0630** [comment]
done
commit a5f7c467421dfdf8db771626c1cfc5558c9f7a5f
