### ISSUE TITLE
Minor suggestion on unit test

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/2048#26]
What you have is:

    def test1(self):
        originallst = right1([[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 2, 2, 2]])

        expectedanswer = [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 2, 4]]

        self.assertEqual(originallst[0], expectedanswer)

Suggestion:

    def test1(self):
        originallst = [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 2, 2, 2]]
        answer = right1(originallist)

        expectedanswer = [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 2, 4]]

        self.assertEqual(answer, expectedanswer)

**Comment by ajkim0630** [comment]
done
commit de6a32aed28d83fae2e2dec0f2f8afb3c1a20b50
