### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/2048#27]
Hi,

Add a file called ".gitignore" and add the following - these will make your repo look cleaner. 

.idea*
__pycache*

After you create this file, you will have to do "git add .ignore" and commit eventually.

**Comment by jybluekim** [comment]
Also, you have a folder called "2048 folder" - what is it? 

If it is not needed then you can git rm it and commit as well.

**Comment by ajkim0630** [comment]
done
