### ISSUE TITLE
BUG: basic problem

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/2048#29]
I don't know where this bug got introduced but.. I am missing a new random number! 

Hello and welcome to 2048! I am your host, Luna. Type 'l', 'r', 'u', 'd', or 'q.' Have fun!

[0, 0, 0, 0]
[0, 2, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
What is your move? r
[0, 0, 0, 0]
[0, 0, 0, 2]
[0, 0, 0, 0]
[0, 0, 0, 0]

**Comment by jybluekim** [comment]
Maybe you can write a test that says the first one and second one should NOT be the same after slide right AND random number add!

**Comment by ajkim0630** [comment]
this is my code

backuplst = lst[:]


        #    direction1 = direction(selfmode,f,lst,counter)

            direction1 = 'r'
            lst = move(direction1,lst)
            if lst == 'Thanks for playing!':
                f.close()
                return ''
            if lst != backuplst:
                lst = new(lst)
                counter += 1

but when I change lst, backuplst changes too for some reason

**Comment by ajkim0630** [comment]
done, i fixed it in the recent commit
