### ISSUE TITLE
Add self-playing mode for testing

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/2048#3]
Add a feature where the computer is playing by itself and generate the trace to a file so we can kind of see what is going on. You can randomize direction (left/right/up/down) or even create some algorithm to solve it!

**Comment by ajkim0630** [comment]
it is almost done, but it automatically dies when all the spots are filled up (in the real game, even if the spots are filled up, you will only die if there is no way to move.)

**Comment by ajkim0630** [comment]
fixed!
