### ISSUE TITLE
Create and write to a log file

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/2048#9]
We need to generate statistics for your runs.

For each run, you need to check the log file (say "stats.csv") exists or not.

If it exists -> add to it (one line)
If not -> create the file, add a header row, then add a line.

Here is an example of a file:

left, right, up, down, total
11, 22, 33, 44, 100
10, 20, 30, 41, 101

Run it 10 times so you would have 10 lines of data in the log file, then post the contents here.

**Comment by ajkim0630** [comment]
done
